/*************************************************************************
 *
 * Copyright 2026, Mechdyne Corporation
 * ALL RIGHTS RESERVED
 *
 * UNPUBLISHED -- Rights reserved under the copyright laws of the United
 * States. Use of a copyright notice is precautionary only and does not
 * imply publication or disclosure.
 *
 * THE CONTENT OF THIS WORK CONTAINS CONFIDENTIAL AND PROPRIETARY
 * INFORMATION OF MECHDYNE CORPORATION. ANY DUPLICATION, MODIFICATION,
 * DISTRIBUTION, OR DISCLOSURE IN ANY FORM, IN WHOLE, OR IN PART, IS
 * STRICTLY PROHIBITED WITHOUT THE PRIOR EXPRESS WRITTEN PERMISSION OF
 * MECHDYNE CORPORATION.
 *
 * Version 4.5.0.4237
 *
 ************************************************************************/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Packages/com.mechdyne.getreal3d/Runtime/Examples/InputSystem/InputSystemExampleActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if ENABLE_INPUT_SYSTEM

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace getReal3D.Examples
{
    public partial class @InputSystemExampleActions: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputSystemExampleActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystemExampleActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""bd3b9a06-2f47-40ca-8f30-1acf111bf14a"",
            ""actions"": [
                {
                    ""name"": ""Clear Cubes"",
                    ""type"": ""Button"",
                    ""id"": ""7f364d44-1631-44bb-89a8-4f8b27d92dad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Add Cubes"",
                    ""type"": ""Button"",
                    ""id"": ""2705394e-ca19-4c29-a73e-620c0fe56b80"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change Cube Scale"",
                    ""type"": ""Value"",
                    ""id"": ""4c65962a-1dda-4dd5-9f8c-b9eea801a701"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0b54bc61-70ad-40d1-a5c2-5551c6f112ca"",
                    ""path"": ""<getReal3D Controller>/ChangeWand"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clear Cubes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fa7f36f-3ab8-4f24-beff-0821424e89fc"",
                    ""path"": ""<getReal3D Controller>/WandButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Add Cubes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dff0ef6b-7eff-4848-ac88-e87729e8ac92"",
                    ""path"": ""<getReal3D Controller>/Forward/axis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change Cube Scale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Gameplay
            m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
            m_Gameplay_ClearCubes = m_Gameplay.FindAction("Clear Cubes", throwIfNotFound: true);
            m_Gameplay_AddCubes = m_Gameplay.FindAction("Add Cubes", throwIfNotFound: true);
            m_Gameplay_ChangeCubeScale = m_Gameplay.FindAction("Change Cube Scale", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Gameplay
        private readonly InputActionMap m_Gameplay;
        private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
        private readonly InputAction m_Gameplay_ClearCubes;
        private readonly InputAction m_Gameplay_AddCubes;
        private readonly InputAction m_Gameplay_ChangeCubeScale;
        public struct GameplayActions
        {
            private @InputSystemExampleActions m_Wrapper;
            public GameplayActions(@InputSystemExampleActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @ClearCubes => m_Wrapper.m_Gameplay_ClearCubes;
            public InputAction @AddCubes => m_Wrapper.m_Gameplay_AddCubes;
            public InputAction @ChangeCubeScale => m_Wrapper.m_Gameplay_ChangeCubeScale;
            public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
            public void AddCallbacks(IGameplayActions instance)
            {
                if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
                @ClearCubes.started += instance.OnClearCubes;
                @ClearCubes.performed += instance.OnClearCubes;
                @ClearCubes.canceled += instance.OnClearCubes;
                @AddCubes.started += instance.OnAddCubes;
                @AddCubes.performed += instance.OnAddCubes;
                @AddCubes.canceled += instance.OnAddCubes;
                @ChangeCubeScale.started += instance.OnChangeCubeScale;
                @ChangeCubeScale.performed += instance.OnChangeCubeScale;
                @ChangeCubeScale.canceled += instance.OnChangeCubeScale;
            }

            private void UnregisterCallbacks(IGameplayActions instance)
            {
                @ClearCubes.started -= instance.OnClearCubes;
                @ClearCubes.performed -= instance.OnClearCubes;
                @ClearCubes.canceled -= instance.OnClearCubes;
                @AddCubes.started -= instance.OnAddCubes;
                @AddCubes.performed -= instance.OnAddCubes;
                @AddCubes.canceled -= instance.OnAddCubes;
                @ChangeCubeScale.started -= instance.OnChangeCubeScale;
                @ChangeCubeScale.performed -= instance.OnChangeCubeScale;
                @ChangeCubeScale.canceled -= instance.OnChangeCubeScale;
            }

            public void RemoveCallbacks(IGameplayActions instance)
            {
                if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IGameplayActions instance)
            {
                foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public GameplayActions @Gameplay => new GameplayActions(this);
        public interface IGameplayActions
        {
            void OnClearCubes(InputAction.CallbackContext context);
            void OnAddCubes(InputAction.CallbackContext context);
            void OnChangeCubeScale(InputAction.CallbackContext context);
        }
    }
}

#endif
